//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penpusher
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PenpusherDatabaseEntities : DbContext
    {
        public PenpusherDatabaseEntities()
            : base("name=PenpusherDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<NewsProvider> NewsProviders { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersArticle> UsersArticles { get; set; }
        public virtual DbSet<UsersNewsProvider> UsersNewsProviders { get; set; }
    }
}
