//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Penpusher
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersArticle
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int ArticleId { get; set; }
        public Nullable<bool> IsFavorite { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsToReadLater { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
